#!/bin/bash

echo "🧪 Widget Testing Guide"
echo "======================"
echo ""
echo "Your main app is working! Now let's test widgets:"
echo ""

echo "📱 OPTION 1: Test on Home Screen (Recommended)"
echo "----------------------------------------------"
echo "1. Open your simulator"
echo "2. Make sure main app has run and loaded data"
echo "3. Go to Home Screen (⌘ + Shift + H)"
echo "4. Long press on empty space"
echo "5. Tap '+' button (top left)"
echo "6. Search 'AdMetrics'"
echo "7. Choose widget size"
echo "8. Add to home screen"
echo ""
echo "✅ Widget should show YOUR REAL DATA:"
echo "   - Balance: ~$43.61"
echo "   - Today's revenue"
echo "   - 7-day chart"
echo ""
echo "❌ If you see placeholder data (like $1234.56):"
echo "   - Main app hasn't saved data yet"
echo "   - Solution: Run main app again, let it load data"
echo ""

echo "🔧 OPTION 2: Test in Xcode (Quick Preview)"
echo "------------------------------------------"
echo "1. In Xcode, change scheme to 'AdMetricsWidgetExtension'"
echo "2. Press ⌘ + R"
echo "3. Choose 'Xcode' from the app list"
echo "4. Click 'Run'"
echo "5. Widget preview window opens"
echo "6. Should show all 3 widget sizes with real data"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "-----------------"
echo ""
echo "Issue: Widget shows placeholder data"
echo "Fix: Run main app first, let it load data, then add widget"
echo ""
echo "Issue: Can't find 'AdMetrics' in widget gallery"
echo "Fix: Make sure you built the AdMetricsWidgetExtension scheme"
echo ""
echo "Issue: Widget shows 'No data available'"
echo "Fix: Open main app, enter API key, let it fetch data"
echo ""

echo "📊 CHECK DATA SHARING"
echo "--------------------"
echo "To verify SharedDataManager is working:"
echo ""
echo "1. Run main app"
echo "2. Check Xcode console for:"
echo "   ✅ Widget data saved successfully"
echo "3. Add widget"
echo "4. Widget should show same data as main app"
echo ""

echo "🎯 QUICK TEST STEPS"
echo "-------------------"
echo "1. ⌘ + R (run main app)"
echo "2. Wait for data to load"
echo "3. Look for '✅ Widget data saved' in console"
echo "4. ⌘ + Shift + H (go to home screen)"
echo "5. Add widget"
echo "6. Check if data matches main app"
echo ""

echo "✨ If widget shows your real balance and stats = SUCCESS! 🎉"
echo ""
